### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by nautilusx** [SufficientlySecure/birthday-adapter#87]
Great app - Thank you.

I think we need a new icon for this app in the material design.

Here is good idea from a FLOOS-theme.
https://gitlab.com/xphnx/twelf_cm12_theme/blob/master/svgs/depot/birthdayadapter.svg

https://gitlab.com/xphnx/twelf_cm12_theme

**Comment by dschuermann** [comment]
We actually already have a new icon here: https://github.com/SufficientlySecure/birthday-adapter/blob/master/Resources/ic_launcher.svg

But no version has been released yet with this one.

**Comment by nautilusx** [comment]
Looks very good. Please release this and the new icon for offline calendar.

**Comment by PanderMusubi** [comment]
If I may say, the icon contains too many details. Perhaps an icon which adheres to Material Design is more stong? Something based on for example https://github.com/google/material-design-icons/blob/master/action/drawable-mdpi/ic_perm_contact_calendar_black_48dp.png If you want I can make a concept.
